### ISSUE TITLE
Aliased color palette

### ISSUE THREAD

**Issue by Finorion** [itsjavi/bootstrap-colorpicker#161]
Aliased color palette not work in mobile devices.
Not change color on tap.

**Comment by berengergermain** [comment]
NB : sorry for my (poor) english ^^

Hello,

I had the same problem. It seems that it is due to the mousedown.colorpicker and touchstart.colorpicker listeners registration. On mobile device touchstart.colorpicker event takes advantages on other mouse listeners and because the listener is registered on the picker top element, mousedown on colorpicker-selectors div is never detected.

What I have done to get it work is separate the registration of the listeners : the first one is for saturation, hue, alpha and color sub-element for the mousedown and the touchstart event. The second one is only for selectors sub-element, only for the mousedown event listener.

This work fine, but it avoid the custom templating feature because we need a static template to target properly the sub-elements...

I hope that can help you :)
