### ISSUE TITLE
colorpicker-selectors stopped working with jQuery 3

### ISSUE THREAD

**Issue by piernik** [itsjavi/bootstrap-colorpicker#182]
In new version colorSelectors are not wokring.
when I change:
`
this.picker.find('.colorpicker-selectors').show();
`
to
`
this.picker.find('.colorpicker-selectors').css('display','block');
`
It is ok.

I'm using jQuery 3.1.1

**Comment by itsjavi** [comment]
@piernik That's an issue with jQuery 3. The show() hide() and toggle() method behaviors have been changed:

https://jquery.com/upgrade-guide/3.0/#breaking-change-show-hide-and-toggle-methods-now-respect-more-stylesheet-changes

This could be solved in a future version using state-classes (like `.hidden`) instead of relying on jQuery's visibility methods.

Meanwhile please stick to jQuery < 3 if possible.
