### ISSUE TITLE
Colors aren't displayed with hexNumberSignPrefix set to false

### ISSUE THREAD

**Issue by ArthurHoaro** [itsjavi/bootstrap-colorpicker#204]
See https://jsfiddle.net/4pppsatn/5/

The color is missing in `input-group-addon` and under the colorpicker.

**Comment by gissf1** [comment]
I also noticed this.  I'm guessing that when it populates the color, it fails to parse the color value due to the lack of '#'.  Everything seems to be fine as long as hexNumberSignPrefix is true.  I ran across this issue at work where we are using this plugin on just a few pages, so I wasn't able to diagnose it further.
